services:
  # Entwicklungsserver mit Hot-Reload
  dev:
    build:
      context: .
      target: dev
    ports:
      - "4000:3000"
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    environment:
      - NODE_ENV=development
      - WATCHPACK_POLLING=true
  # Production Build
  prod:
    build:
      context: .
      target: prod
    ports:
      - "4001:3000"
    environment:
      - NODE_ENV=production

volumes:
  node_modules:
